apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: minio4
  name: minio4
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio4
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-compose-default: "true"
        io.kompose.service: minio4
    spec:
      containers:
        - args:
            - server
            - --console-address
            - :9001
            - http://minio{1...4}/data{1...2}
          image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9000/minio/health/live
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: minio4
          ports:
            - containerPort: 9000
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /data1
              name: data4-1
            - mountPath: /data2
              name: data4-2
      hostname: minio4
      restartPolicy: Always
      volumes:
        - name: data4-1
          persistentVolumeClaim:
            claimName: data4-1
        - name: data4-2
          persistentVolumeClaim:
            claimName: data4-2
status: {}
